In [1]:
import sys
sys.path.append('/Volumes/osx_main2/PythonProject/stock-predict')

In [2]:
from src.data.dataset import DataSet

In [3]:
# input_path = '/Volumes/osx_sub/data/stock_data/test'
# output_path = '/Volumes/osx_sub/data/stock_data/datset_test'
# input_path = '/Volumes/osx_sub/data/stock_data/stock_data'
# output_path = '/Volumes/osx_sub/data/stock_data/20seq_data'

In [4]:
input_path = '/Volumes/osx_sub/data/stock_data/test'
output_path = '/Volumes/osx_sub/data/stock_data/dataset_test'
# new
dataset2 = DataSet(data_path=input_path, data_status=0, output_path=output_path, label_price=0, sequence_length=20)

Loading stock data by compnay name
Elapsed time: 0:00:01.634760
Label Range: {0: [-30, -20], 1: [-20, -10], 2: [-10, 0], 3: [0, 10], 4: [10, 20], 5: [20, 31]}
Data sequence created. saving now...
Elapsed time: 0:00:18.785526
77789
77789


In [4]:
input_path = '/Volumes/osx_sub/data/stock_data/test'
output_path = '/Volumes/osx_sub/data/stock_data/dataset_test'
# new
dataset2 = DataSet(data_path=input_path, data_status=0, output_path=output_path, label_price=0, sequence_length=20)

Loading stock data by compnay name
Time elapsed: 0:00:03.509708
Label Range: {0: [-30, -20], 1: [-20, -10], 2: [-10, 0], 3: [0, 10], 4: [10, 20], 5: [20, 31]}
Data sequence created. saving now...
Elapsed time: 0:00:20.598332
77789
77789


In [9]:
print(dataset2.queries.shape)
print(dataset2.labels.shape)

(77789, 20, 7)
(77789,)


In [5]:
input_path = '/Volumes/osx_sub/data/stock_data/stock_data'
output_path = '/Volumes/osx_sub/data/stock_data/20seq_data'
# new
dataset = DataSet(data_path=input_path, data_status=0, output_path=output_path, label_price=0, sequence_length=20)

Loading stock data by compnay name
Elapsed time: 0:02:13.926655
Label Range: {0: [-30, -20], 1: [-20, -10], 2: [-10, 0], 3: [0, 10], 4: [10, 20], 5: [20, 31]}
Data sequence created. saving now...
Data sequence created. saving now...
Data sequence created. saving now...
Data sequence created. saving now...
Data sequence created. saving now...
Data sequence created. saving now...
Data sequence created. saving now...
Elapsed time: 0:56:18.912791
6767608
6767608


In [8]:
print(dataset.queries.shape)
print(dataset.labels.shape)

(6767608, 20, 7)
(6767608,)


In [12]:
import numpy as np
from os.path import join

In [ ]:
# result = dict()
# result['queries'] = dataset.queries
# result['labels'] = dataset.labels
# np.save(join('/Volumes/osx_sub/data/stock_data/20seq_data', 'labelled_data_2', 'x_y'), result)

In [ ]:
np.save(join('/Volumes/osx_sub/data/stock_data/20seq_data', 'labelled_data_2', 'x'), dataset.queries)

In [4]:
# new
dataset = DataSet(data_path=input_path, data_status=0, output_path=output_path, label_price=0, sequence_length=20)

Loading stock data by compnay name
Label Range: {0: [-30, -20], 1: [-20, -10], 2: [-10, 0], 3: [0, 10], 4: [10, 20], 5: [20, 31]}
[[3 1 1 ... 2 3 2]
 [1 1 1 ... 3 2 2]
 [1 1 3 ... 2 2 3]
 ...
 [3 2 3 ... 3 2 2]
 [2 3 2 ... 2 2 3]
 [3 2 3 ... 2 3 3]]
<class 'numpy.ndarray'>
[3 1 1 1 3 3 2 4 4 1 2 3 4 2 3 2 2 2 3 2]
<class 'numpy.ndarray'>
77789
77789


In [4]:
# old
# dataset = DataSet_old(data_path=input_path, sequence_length=20)

Loading stock data by compnay name
Reformat by given sequence length
Label Range: {0: [-30, -20], 1: [-20, -10], 2: [-10, 0], 3: [0, 10], 4: [10, 20], 5: [20, 31]}
[[3 1 1 ... 2 3 2]
 [1 1 1 ... 3 2 2]
 [1 1 3 ... 2 2 3]
 ...
 [3 2 3 ... 3 2 2]
 [2 3 2 ... 2 2 3]
 [3 2 3 ... 2 3 3]]
<class 'numpy.ndarray'>
[3 1 1 1 3 3 2 4 4 1 2 3 4 2 3 2 2 2 3 2]
<class 'numpy.ndarray'>
77789
77789
